name: Integration Tests

on:
  push:
    branches: [ main ]
  pull_request:

env:
  DOCKER_API_VERSION: 1.48

permissions:
  contents: read

jobs:
  jvm:
    strategy:
      fail-fast: false
      matrix:
        docker_version:
          - "29.2.1"
    runs-on: ubuntu-latest
    name: JVM
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup Docker CE v${{ matrix.docker_version }}
        uses: docker/setup-docker-action@v4.6.0
        with:
          version: v${{ matrix.docker_version }}

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Prune Docker System
        run: docker system prune -a -f

      - name: Run Tests
        run: ./gradlew jvmTest
  native:
    if: ${{ vars.NATIVE_TESTS_ENABLED == 'true' }}
    strategy:
      fail-fast: false
      matrix:
        docker_version:
          - "29.2.1"
        os:
          - name: Linux (x64)
            runner: ubuntu-22.04
            sourceset: linuxX64

          - name: Linux (ARM)
            runner: ubuntu-22.04-arm
            sourceset: linuxArm64

          - name: macOS (Intel)
            runner: macos-15-intel
            sourceset: macosX64

          - name: macOS (Apple Silicon)
            runner: macos-15
            sourceset: macosArm64

          - name: Windows
            runner: windows-2025
            sourceset: mingwX64

    runs-on: ${{ matrix.os.runner }}
    name: Native - ${{ matrix.os.name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup Docker CE v${{ matrix.docker_version }}
        uses: docker/setup-docker-action@v4.6.0
        if: ${{ matrix.os.runner != 'macosX64' && matrix.os.runner != 'macosArm64' }}
        with:
          version: v${{ matrix.docker_version }}

      - name: Setup Homebrew
        uses: Homebrew/actions/setup-homebrew@master
        if: ${{ matrix.os.runner == 'macosX64' || matrix.os.runner == 'macosArm64' }}

      - name: Setup Docker
        if: ${{ matrix.os.runner == 'macosX64' || matrix.os.runner == 'macosArm64' }}
        run: |
          brew install docker
          colima start
          docker version
          colima version

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Prune Docker System
        run: docker system prune -a -f

      - name: Run Tests
        run: ./gradlew ${{ matrix.os.sourceset }}Test
